export * from "./types.js";
export * from "./compose.js";
export * from "./base.js";
export {
  SlotsProvider,
  SlotHost,
  useSlotFillers,
} from "./slots.js";
export {
  apiKeysModule,
  useApiKeys,
  useCreateApiKey,
  useRevokeApiKey,
  useRotateApiKey,
  ApiKeysError,
  KEYS_QUERY_KEY,
  type ApiKey,
  type ApiKeyWithSecret,
  type CreateApiKeyInput,
} from "./api-keys/index.js";
export {
  makeUsersModule,
  UsersList,
  UserDetail,
  useUsers,
  useUser,
  useUpdateUser,
  useDeactivateUser,
  useInviteUser,
  InviteNotImplementedError,
  UsersError,
  USERS_QUERY_KEY,
  type User,
  type UserRole,
  type UserStatus,
  type UpdateUserInput,
  type InviteUserInput,
  type MakeUsersModuleOptions,
} from "./users/index.js";
export {
  settingsModule,
  SETTINGS_SECTIONS_SLOT,
  SettingsProfile,
  SettingsSecurity,
  SettingsSectionsHost,
  useActiveSessions,
  useChangePassword,
  useRevokeSession,
  useSignOutEverywhere,
  SESSIONS_QUERY_KEY,
} from "./settings/index.js";
export {
  accountsModule,
  AccountsList,
  AccountDetail,
  AccountOverviewTab,
  ACCOUNTS_DETAIL_TABS_SLOT,
  ACCOUNTS_LIST_COLUMNS_SLOT,
  AccountTabProvider,
  useAccountTabContext,
  useAccounts,
  useAccount,
  useUpdateAccount,
  useDeleteAccount,
  AccountsError,
  ACCOUNTS_QUERY_KEY,
  accountQueryKey,
  type Account,
  type UpdateAccountInput,
  type UseAccountsOptions,
  type AccountsListResponse,
  type AccountsListColumn,
} from "./accounts/index.js";
export {
  peopleModule,
  PeopleList,
  PersonDetail,
  usePeople,
  usePerson,
  useUpdatePerson,
  useDeletePerson,
  PeopleError,
  PEOPLE_QUERY_KEY,
  personQueryKey,
  type Person,
  type UpdatePersonInput,
  type UsePeopleOptions,
  type PersonsListResponse,
} from "./people/index.js";
export {
  pipelinesModule,
  PipelinesKanban,
  PipelinePicker,
  DealDialog,
  usePipelines,
  usePipeline,
  useStagesForPipeline,
  useDealsForPipeline,
  useCreateDeal,
  useUpdateDeal,
  useDeleteDeal,
  applyOptimisticDealPatch,
  invalidateDealsForPipeline,
  PipelinesError,
  PIPELINES_QUERY_KEY,
  STAGES_QUERY_KEY,
  DEALS_QUERY_KEY,
  pipelineQueryKey,
  stagesForPipelineQueryKey,
  dealsForPipelineQueryKey,
  dealQueryKey,
  type Pipeline,
  type Stage,
  type Deal,
  type DealsFilter,
  type UseDealsOptions,
  type CreateDealInput,
  type UpdateDealInput,
  type PipelinesListResponse,
  type StagesListResponse,
  type DealsListResponse,
  type StageTerminalKind,
} from "./pipelines/index.js";
export { usePersistedColumns } from "./use-persisted-columns.js";
